version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pix
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
      image: docker.io/bitnami/kafka:3.4
      ports:
        - "9092:9092"
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      depends_on:
        - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local