version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres          # Nome do usuário
      POSTGRES_PASSWORD: postgres       # Senha do usuário
      POSTGRES_DB: pix                  # Nome do banco de dados a ser criado
    ports:
      - "5432:5432"                     # Mapeia a porta 5432 do contêiner para a porta 5432 da máquina host
    volumes:
      - ./data:/var/lib/postgresql/data # Persistência dos dados
